#pragma once

#include <map>
#include <string>

enum class ErrorCode {
    UNKNOWN_ERROR,
    TYPE_UNKNOWN,
    TYPE_UNKNOWN_CONSTRUCTOR,
    TYPE_UNKNOWN_FIELD,
    TYPE_UNKNOWN_FUNCTION,
    TYPE_COERCION_IMPLICIT_FAILED,
    TYPE_INFER_FAILED,
    BINARY_OP_UNKNOWN,
    FUNCTION_UNKNOWN,
    FUNCTION_MULTIPLE_RETURN_TYPES,
    VARIABLE_UNDECLARED,
    VARIABLE_INFER_FAILED,
    VARIABLE_ALREADY_DECLARED,
    SYNTAX_UNEXPECTED_TOKEN,
    STATIC_REF_UNKNOWN,
    ENUM_UNKNOWN_VALUE,
    SYNTAX_ERROR,
    WHEN_UNUSED_ENUM_VALUE,
    WHEN_MULTIPLE_RETURN_TYPES,
    VALUE_CANNOT_BE_NULL,
    VALUE_POSSIBLY_NULL,
    ASSIGN_TYPE_MISMATCH,
    OUT_OF_RANGE,
};

extern const std::map<ErrorCode, std::string> ErrorTable;
